#!/usr/bin/env python3
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.

import sys
import re
import os


def main():
    ref = os.environ.get("GITHUB_REF")
    info = {"isdistro": "false", "ref": ref}
    m = re.match(
        "^refs/heads/"
        "(?P<image>"
        "(?P<mirror>[^-]+)-(?P<dist>[^-]+)-(?P<arch>[^-]+)"
        "(-(?P<variant>[^-]+))?)",
        ref,
    )
    if ref and m:
        info["isdistro"] = "true"
        for k in ("image", "mirror", "dist", "arch", "variant"):
            info[k] = m.group(k)
    for k, v in info.items():
        sys.stdout.write("name={}::{}\n".format(k, v))
        sys.stdout.write("::set-output name={}::{}\n".format(k, v))


if __name__ == "__main__":
    main()
