#!/bin/bash

set -e -o pipefail

usage="Usage: $0 [-h] [-k] [-i <image name>] [-t <variant>] [distribution [architecture]]"

keepdir=false

while getopts ":ki:t:h" opt; do
    case "$opt" in
        k) keepdir=true;;
        i) image="$OPTARG";;
        t) variant="$OPTARG";;
        h) echo "$usage"; exit 0;;
        \?) printf "Invalid argument\\n%s\\n" "$usage" >&2; exit 1;;
    esac
done
shift $((OPTIND-1))

dist=${1-jessie}
arch=${2-amd64}

case "$dist" in
    potato)  mirror=http://archive.debian.org/debian;;
    woody)   mirror=http://archive.debian.org/debian;;
    sarge)   mirror=http://archive.debian.org/debian;;
    etch)    mirror=http://archive.debian.org/debian;;
    lenny)   mirror=http://archive.debian.org/debian;;
    squeeze) mirror=http://archive.debian.org/debian;;
    *)       mirror=http://deb.debian.org/debian;;
esac

# Create tmp dir, setup cleanup:
dir="$(mktemp -d --suffix=-rootfs -p "$PWD")"
function cleanup {
    if ! "$keepdir"; then
        sudo umount -l "$dir/sys" "$dir/proc" 2>/dev/null || :
        sudo rm -rf "$dir"
    fi
}
trap cleanup EXIT

# Build debootstrap commnad-line

name=debian-${dist}-${arch}
image=${image-"$name"}

cmd=(sudo debootstrap)
if [ -n "$variant" ]; then
   cmd+=("--variant=$variant")
fi
cmd+=("--no-check-gpg" "--arch=$arch" "$dist" "$dir" "$mirror")

# Run:

set -x

: name="$name", image="$image"

if ! "${cmd[@]}"; then
     cat "$dir/debootstrap/debootstrap.log"
     false
fi
if [ -d "$dir/var/lib/apt/lists" ]; then
    sudo find "$dir/var/lib/apt/lists" -type f -delete
fi
msg="Created by https://github.com/lpenz/docker-debian-releases"
if [ -f "$dir/usr/lib/os-release" ]; then
    # shellcheck disable=SC1090
    . "$dir/usr/lib/os-release"
    msg="$PRETTY_NAME for $arch image created by https://github.com/lpenz/docker-debian-releases"
fi
sudo tar -C "$dir" -c . | \
    docker import \
           -m "$msg" \
           -c 'CMD ["bash"]' \
           - "$image"
docker inspect "$image"
